- hosts: server3
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes   
   
    - name: Install Postgresql
      apt: name=postgresql state=latest

      notify:
        - restart postgresql

  handlers:
    - name: restart postgresql
      service: name=postgresql state=reloaded
