- hosts: server2
  become: yes
  tasks:

    - name: update
      apt: update_cache=yes   
   
    - name: Install Apache2
      apt: name=apache2 state=latest

      notify:
        - restart apache2

  handlers:
    - name: restart apache2
      service: name=apache2 state=reloaded
