- hosts: ubuntu
  become: yes
  tasks:

    - name: Install zabbix-agent on Ubuntu
      apt:
         name=zabbix-agent
         state=latest

      when:
         ansible_os_family == "Debian"


    - name: Install zabbix release package
      apt:
        deb: https://repo.zabbix.com/zabbix/6.0/ubuntu/pool/main/z/zabbix-release/zabbix-release_6.0-4+ubuntu22.04_all.deb

      notify:
         zabbix-agent systemd

  handlers:
    - name: zabbix-agent systemd
      systemd:
       name: zabbix-agent.service
       enabled: yes
       state: started
